[tool.poetry]
name = "sync_ics2gcal"
version = "0.1.5"
description = "Sync ics file with Google calendar"
authors = ["Dmitry Belyaev <b4tm4n@mail.ru>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/b4tman/sync_ics2gcal"
repository = "https://github.com/b4tman/sync_ics2gcal"
keywords = ["icalendar", "sync", "google", "calendar"]
classifiers = [
    'License :: OSI Approved :: MIT License',
    'Operating System :: OS Independent',
    'Programming Language :: Python :: 3.11',
    'Programming Language :: Python :: 3.12',
    'Programming Language :: Python :: 3.13',
]

[tool.poetry.dependencies]
python = "^3.11"
google-auth = "2.41.1"
google-api-python-client = "2.183.0"
icalendar = "6.3.1"
pytz = "2025.2"
PyYAML = "6.0.3"
fire = "0.7.1"

[tool.poetry.group.dev]
optional = true

[tool.poetry.group.docs]
optional = true

[tool.poetry.group.dev.dependencies]
pytest = ">=8.1,<9.0"
flake8 = ">=7.0.4,<8.0.0"
black = ">=25.0,<26.0"
mypy = ">=1.16.1"
types-python-dateutil = ">=2.9.0.20250516"
types-pytz = ">=2025.2.0.20250516"
types-PyYAML = "^6.0.12.20250516"
lxml = ">=5.4.0,<7.0.0"

[tool.poetry.group.docs.dependencies]
sphinx = ">=8.2,<9.0"
myst-parser = ">=4,<5"
sphinx-rtd-theme = ">=3.0.2,<4.0.0"
sphinx-copybutton = "^0.5.2"
sphinx-design = ">=0.6,<0.7"

[tool.poetry.scripts]
sync-ics2gcal = "sync_ics2gcal.sync_calendar:main"
manage-ics2gcal = "sync_ics2gcal.manage_calendars:main"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[[tool.mypy.overrides]]
module = [
    'icalendar',
    'google.*',
    'googleapiclient',
    'fire'
]
ignore_missing_imports = true
