name: Upload Python Package

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Upgrade pip
      run: python -m pip install --upgrade pip
    - name: Load cached Poetry installation
      uses: actions/cache@v2
      with:
        path: ~/.local
        key: poetry-0
    - name: Install Poetry
      uses: snok/install-poetry@v1
    - name: Install deps
      run: poetry install
    - name: Build
      run: poetry build
    - name: Publish
      env:
        REPO_USERNAME: __token__
        REPO_PASSWORD: ${{ secrets.pypi_token }}
      run: |
        poetry publish -n -u $REPO_USERNAME -p $REPO_PASSWORD
